sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker --version

script:
  - docker build -t fraudmarc/fraudmarc-ce .
  - docker build -t fraudmarc/fraudmarc-ce-install -f installer/Dockerfile .

after_script:
  - docker images

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
